/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnimemory_MemoryTestNative */

#ifndef _Included_com_example_jnimemory_MemoryTestNative
#define _Included_com_example_jnimemory_MemoryTestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnimemory_MemoryTestNative
 * Method:    allocateMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_jnimemory_MemoryTestNative_allocateMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_jnimemory_MemoryTestNative
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_jnimemory_MemoryTestNative_freeMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_jnimemory_MemoryTestNative
 * Method:    setMemory
 * Signature: (JJB)V
 */
JNIEXPORT void JNICALL Java_com_example_jnimemory_MemoryTestNative_setMemory
  (JNIEnv *, jclass, jlong, jlong, jbyte);

/*
 * Class:     com_example_jnimemory_MemoryTestNative
 * Method:    getResidentSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_jnimemory_MemoryTestNative_getResidentSize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
