package com.example.jnimemory;

public class MemoryTestNative {
    // Loads the shared library generated by JNI.
    static {
        System.loadLibrary("memory"); 
    }

    /**
     * Allocate a block of native memory of size bytes. 
     * Returns a "handle" (long) to the allocated memory region.
     */
    public static native long allocateMemory(long size);

    /**
     * Free a previously allocated block of native memory.
     */
    public static native void freeMemory(long address);

    /**
     * Free a previously allocated block of native memory.
     */
    public static native void setMemory(long address, long size, byte value);

    /**
     * Get the resident set size (RSS) of the current process.
     * @return the resident set size in bytes
     */
    public static native long getResidentSize();
}
